# Portable private AI company runtime experiment.

__version__ = '0.4.0'

from .task_graph import (
    GRAPH_SCHEMA_VERSION,
    DECISION_SCHEMA_VERSION,
    RESULT_SCHEMA_VERSION,
    EXECUTION_MODEL,
    TaskGraph,
    TaskGraphNode,
    TaskGraphCheck,
    TaskGraphDecision,
    IntentExecutionResult,
    build_task_graph,
    decide_task_graph,
    validate_graph_dag,
    execute_intent,
    load_budget_truth,
)

from .state_spine import (
    StateSpineError,
    UnifiedIds,
    CanonicalMemoryReader,
    SQLiteStateIndex,
    StateSpineTaskLedger,
    RestartSafeStateSpine,
)

from .novel_mvp import (
    NOVEL_MVP_REQUEST_SCHEMA,
    NOVEL_MVP_RUN_SCHEMA,
    NOVEL_CHAPTER_DRAFT_SCHEMA,
    NOVEL_QUALITY_REPORT_SCHEMA,
    NOVEL_ACCEPTED_ARTIFACT_SCHEMA,
    NOVEL_CAPABILITIES,
    DEPARTMENT_ID,
    NovelMvpError,
    DraftProvider,
    DeterministicLocalDraftProvider,
    NovelBusinessExecutor,
    NovelMvpService,
    mount_novel_mvp_routes,
    validate_novel_mvp_request,
)

from .economic_ledger import (
    EconomicLedger,
    EconomicLedgerError,
    EconomicBudgetTruth,
    EconomicBudgetPolicy,
    LegacyBudgetLedgerAdapter,
    SCHEMA_ENVELOPE,
    SCHEMA_POLICY,
    SCHEMA_RESERVATION,
    SCHEMA_COST,
    SCHEMA_WORK,
    SCHEMA_VERSION,
    SCHEMA_PLATFORM,
    SCHEMA_SETTLEMENT,
    SCHEMA_SUMMARY,
    SCHEMA_EXPORT,
)

from .platform_adapter import (
    PlatformAdapterError,
    PlatformAdapterRegistry,
    PlatformPolicy,
    PlatformAuthorizationLease,
    LocalShadowPlatformAdapter,
    FakeShadowTransport,
    DenyAllShadowTransport,
    build_default_registry,
    ALLOWED_MODES,
    ALLOWED_ACTIONS,
    SCHEMA_POLICY as PLATFORM_SCHEMA_POLICY,
    SCHEMA_CAPABILITY,
    SCHEMA_LEASE,
    SCHEMA_REQUEST,
    SCHEMA_ATTEMPT,
    SCHEMA_CHECKPOINT,
    SCHEMA_RECEIPT,
    SCHEMA_STATE,
    SCHEMA_EXPORT as PLATFORM_SCHEMA_EXPORT,
)

from .publication import (
    PublicationService,
    PUBLICATION_DEPT_ID,
)

__all__ = [
    '__version__',
    'GRAPH_SCHEMA_VERSION',
    'DECISION_SCHEMA_VERSION',
    'RESULT_SCHEMA_VERSION',
    'EXECUTION_MODEL',
    'TaskGraph',
    'TaskGraphNode',
    'TaskGraphCheck',
    'TaskGraphDecision',
    'IntentExecutionResult',
    'build_task_graph',
    'decide_task_graph',
    'validate_graph_dag',
    'execute_intent',
    'load_budget_truth',
    'StateSpineError',
    'UnifiedIds',
    'CanonicalMemoryReader',
    'SQLiteStateIndex',
    'StateSpineTaskLedger',
    'RestartSafeStateSpine',
    'NOVEL_MVP_REQUEST_SCHEMA',
    'NOVEL_MVP_RUN_SCHEMA',
    'NOVEL_CHAPTER_DRAFT_SCHEMA',
    'NOVEL_QUALITY_REPORT_SCHEMA',
    'NOVEL_ACCEPTED_ARTIFACT_SCHEMA',
    'NOVEL_CAPABILITIES',
    'DEPARTMENT_ID',
    'NovelMvpError',
    'DraftProvider',
    'DeterministicLocalDraftProvider',
    'NovelBusinessExecutor',
    'NovelMvpService',
    'mount_novel_mvp_routes',
    'validate_novel_mvp_request',
    'EconomicLedger',
    'EconomicLedgerError',
    'EconomicBudgetTruth',
    'EconomicBudgetPolicy',
    'LegacyBudgetLedgerAdapter',
    'SCHEMA_ENVELOPE',
    'SCHEMA_POLICY',
    'SCHEMA_RESERVATION',
    'SCHEMA_COST',
    'SCHEMA_WORK',
    'SCHEMA_VERSION',
    'SCHEMA_PLATFORM',
    'SCHEMA_SETTLEMENT',
    'SCHEMA_SUMMARY',
    'SCHEMA_EXPORT',
    'PlatformAdapterError',
    'PlatformAdapterRegistry',
    'PlatformPolicy',
    'PlatformAuthorizationLease',
    'LocalShadowPlatformAdapter',
    'FakeShadowTransport',
    'DenyAllShadowTransport',
    'build_default_registry',
    'ALLOWED_MODES',
    'ALLOWED_ACTIONS',
    'PLATFORM_SCHEMA_POLICY',
    'SCHEMA_CAPABILITY',
    'SCHEMA_LEASE',
    'SCHEMA_REQUEST',
    'SCHEMA_ATTEMPT',
    'SCHEMA_CHECKPOINT',
    'SCHEMA_RECEIPT',
    'SCHEMA_STATE',
    'PLATFORM_SCHEMA_EXPORT',
    'PublicationService',
    'PUBLICATION_DEPT_ID',
    'ProviderRegistry',
    'RoutingModelProvider',
    'DeepSeekProvider',
    'ProviderHealthManager',
    'ModelProvider',
    'ModelRequest',
    'ModelMessage',
    'ModelResult',
    'ModelUsage',
    'resolve_secret_reference',
    'build_runtime_provider',
    'NovelOperationsService',
    'NovelOperationsError',
    'sha256_text',
]

from .providers import (  # noqa: E402
    ProviderRegistry,
    RoutingModelProvider,
    DeepSeekProvider,
    ProviderHealthManager,
    ModelProvider,
    ModelRequest,
    ModelMessage,
    ModelResult,
    ModelUsage,
    resolve_secret_reference,
    build_runtime_provider,
)

from .novel_operations import (  # noqa: E402
    NovelOperationsService,
    NovelOperationsError,
    sha256_text,
)
